Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.hostname = "chrony.lab.com"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "chrony"
    vb.cpus = 1
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
end
